"""add news_feed to building model

Revision ID: c08efe9c534d
Revises: b197e795af79
Create Date: 2026-02-17 23:27:43.302618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08efe9c534d'
down_revision = 'b197e795af79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_feed', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_column('news_feed')

    # ### end Alembic commands ###
